/**
 * @fileOverview Analyzes category performance.
 *
 * - analyzeCategories - A function that triggers the category analysis process.
 * - AnalyzeCategoriesInput - The input type for the analyzeCategories function.
 * - AnalyzeCategoriesOutput - The return type for the analyzeCategories function.
 */

import { ai } from "@/ai/genkit";
import { withRetries } from "@/ai/utils";
import { z } from "zod";

const AnalyzeCategoriesInputSchema = z.object({
    datasetId: z.string().describe("The ID of the dataset to analyze."),
});
export type AnalyzeCategoriesInput = z.infer<
    typeof AnalyzeCategoriesInputSchema
>;

const AnalyzeCategoriesOutputSchema = z.object({
    categories: z
        .array(
            z.object({
                categoryName: z.string().describe("The name of the category."),
                totalRevenue: z
                    .number()
                    .describe("The total revenue generated by this category."),
                totalUnitsSold: z
                    .number()
                    .describe(
                        "The total number of units sold in this category.",
                    ),
                topProduct: z
                    .string()
                    .describe("The top-selling product in this category."),
                growthRate: z
                    .number()
                    .describe(
                        "The growth rate of this category as a percentage.",
                    ),
            }),
        )
        .describe("A list of category performance metrics."),
});
export type AnalyzeCategoriesOutput = z.infer<
    typeof AnalyzeCategoriesOutputSchema
>;

export async function analyzeCategories(
    input: AnalyzeCategoriesInput,
): Promise<AnalyzeCategoriesOutput> {
    return analyzeCategoriesFlow(input);
}

const analyzeCategoriesPrompt = ai.definePrompt({
    name: "analyzeCategoriesPrompt",
    input: { schema: AnalyzeCategoriesInputSchema },
    output: { schema: AnalyzeCategoriesOutputSchema },
    model: "googleai/gemini-2.5-flash",
    config: {
        responseMimeType: "application/json",
    },
    prompt: `You are an expert retail analyst acting as a data simulation engine.

  Your task is to simulate running a category performance analysis on a dataset.
  Based on the dataset ID, generate a realistic but synthetic set of category data, including total revenue, total units sold, top product, and growth rate.

  Return the top 5-10 categories in the specified JSON format.
  Dataset ID: {{{datasetId}}}`,
});

const analyzeCategoriesFlow = ai.defineFlow(
    {
        name: "analyzeCategoriesFlow",
        inputSchema: AnalyzeCategoriesInputSchema,
        outputSchema: AnalyzeCategoriesOutputSchema,
    },
    async (input) => {
        const result = await withRetries(async () => {
            const { output } = await analyzeCategoriesPrompt(input);
            return output!;
        });
        return result;
    },
);
