/**
 * @fileOverview Analyzes category performance.
 *
 * - analyzeCategories - A function that triggers the category analysis process.
 * - AnalyzeCategoriesInput - The input type for the analyzeCategories function.
 * - AnalyzeCategoriesOutput - The return type for the analyzeCategories function.
 */

import { ai } from "@/ai/genkit";
import { withRetries } from "@/ai/utils";
import { z } from "zod";

const AnalyzeCategoriesInputSchema = z.object({
    datasetId: z.string().describe("The ID of the dataset to analyze."),
    csvData: z
        .string()
        .describe(
            "A CSV sample of the dataset including headers and up to 200 rows.",
        ),
});
export type AnalyzeCategoriesInput = z.infer<
    typeof AnalyzeCategoriesInputSchema
>;

const AnalyzeCategoriesOutputSchema = z.object({
    categories: z
        .array(
            z.object({
                categoryName: z.string().describe("The name of the category."),
                totalRevenue: z
                    .number()
                    .describe("The total revenue generated by this category."),
                totalUnitsSold: z
                    .number()
                    .describe(
                        "The total number of units sold in this category.",
                    ),
                topProduct: z
                    .string()
                    .describe("The top-selling product in this category."),
                growthRate: z
                    .number()
                    .describe(
                        "The growth rate of this category as a percentage.",
                    ),
            }),
        )
        .describe("A list of category performance metrics."),
});
export type AnalyzeCategoriesOutput = z.infer<
    typeof AnalyzeCategoriesOutputSchema
>;

export async function analyzeCategories(
    input: AnalyzeCategoriesInput,
): Promise<AnalyzeCategoriesOutput> {
    return analyzeCategoriesFlow(input);
}

const analyzeCategoriesPrompt = ai.definePrompt({
    name: "analyzeCategoriesPrompt",
    input: { schema: AnalyzeCategoriesInputSchema },
    output: { schema: AnalyzeCategoriesOutputSchema },
    model: "googleai/gemini-2.5-flash",
    config: {
        responseMimeType: "application/json",
    },
    prompt: `You are an expert retail analyst.

Your task is to analyze the real sales data below and compute category performance metrics.
Use the "category" column to group products, and calculate total revenue, total units sold, the top-selling product, and growth rate for each category.
If there is no explicit growth data, estimate growth rate based on date trends in the data.

Dataset ID: {{{datasetId}}}

--- BEGIN CSV DATA ---
{{{csvData}}}
--- END CSV DATA ---

Return the top 5-10 categories in the specified JSON format.`,
});

const analyzeCategoriesFlow = ai.defineFlow(
    {
        name: "analyzeCategoriesFlow",
        inputSchema: AnalyzeCategoriesInputSchema,
        outputSchema: AnalyzeCategoriesOutputSchema,
    },
    async (input) => {
        const result = await withRetries(async () => {
            const { output } = await analyzeCategoriesPrompt(input);
            return output!;
        });
        return result;
    },
);
